### PR TITLE
Added new project w/screenshot to showcase.html

### PR DESCRIPTION
**Pull request by amandavisconti**
Added my Infinite Ulysses project (Annotator + voting/favoriting) link, description, and screenshot to the end of the list on showcase.html. Description links to screenshot PNG added to /images. Annotator rocks!

### CODE REVIEW

**Comment by tilgovi** [comment]
Nice!

**Comment by BigBlueHat** [comment]
@tilgovi wow! Weren't we talking about annotating Ulysses together sometime soon? :astonished:  

Great project @amandavisconti :exclamation:  Thanks for sharing.

**Comment by tilgovi** [comment]
We were!

**Comment by amandavisconti** [comment]
Thanks @tilgovi & @BigBlueHat!

**Pull request merged**
